/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/panda.gltf 
Author: theamazingdonovan207 (https://sketchfab.com/theamazingdonovan207)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/po-kung-fu-panda-chi-master-bd26a456aac54820bc6896be3c97f119
Title: Po (Kung Fu Panda: Chi Master)
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useSelector } from 'react-redux'

const Panda = (props) => {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/panda.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group)

  const choice = useSelector((state) => state.choice.value)

  useEffect(()=>{
    actions[names[choice]].reset().fadeIn(0.5).play()

  },[choice])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="po_range_with_animfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" scale={50}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_85" position={[36.437, 32.122, 0.594]} rotation={[-Math.PI / 2, 0, 0]} scale={50}>
                      {/* <mesh name="hero05_weapon_02_WeaponCel1_0" geometry={nodes.hero05_weapon_02_WeaponCel1_0.geometry} material={materials.WeaponCel1} /> */}
                    </group>
                    <group name="Object_87" rotation={[-Math.PI / 2, 0, 0]} scale={50} />
                    <group name="Object_89" rotation={[-Math.PI / 2, 0, 0]} scale={50} />
                    {/* <group name="Object_91" rotation={[-Math.PI / 2, 0, 0]} scale={50}>
                      <mesh name="hero05_weapon_WeaponCel_0" geometry={nodes.hero05_weapon_WeaponCel_0.geometry} material={materials.WeaponCel} />
                    </group> */}
                    <skinnedMesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.BodyCel} skeleton={nodes.Object_88.skeleton} />
                    <skinnedMesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.SkinCel} skeleton={nodes.Object_90.skeleton} />
                  </group>
                </group>
                <group name="hero05_weapon_02" position={[36.437, 32.122, 0.594]} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
                <group name="hero05_body" rotation={[-Math.PI / 2, 0, 0]} scale={50} />
                <group name="hero05_skin" rotation={[-Math.PI / 2, 0, 0]} scale={50} />
                {/* <group name="hero05_weapon" rotation={[-Math.PI / 2, 0, 0]} scale={50} /> */}
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Panda

useGLTF.preload('./models/panda.gltf')
